// Typelizer digest 6874a8f100df0a7f8894f49ebddf1039
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from './runtime'
import { buildUrl } from './runtime'

export default {
  /** POST /projects/:project_id/api_keys */
  create: (
    params: { projectId: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'post'> => ({
    url: buildUrl('/projects/:project_id/api_keys', params, options),
    method: 'post',
  }),

  /** DELETE /api_keys/:id */
  destroy: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'delete'> => ({
    url: buildUrl('/api_keys/:id', params, options),
    method: 'delete',
  }),
}
