// Typelizer digest 305bf63f750d861cd85691b83f3e1cc6
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from './runtime'
import { buildUrl } from './runtime'

export default {
  /** POST /projects */
  create: (options?: RouteOptions): RouteDefinition<'post'> => ({
    url: buildUrl('/projects', {}, options),
    method: 'post',
  }),

  /** GET /projects/:id/edit */
  edit: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/projects/:id/edit', params, options),
    method: 'get',
  }),

  /** GET /projects/:id */
  show: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/projects/:id', params, options),
    method: 'get',
  }),

  /** PATCH /projects/:id */
  update: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'patch'> => ({
    url: buildUrl('/projects/:id', params, options),
    method: 'patch',
  }),

  /** DELETE /projects/:id */
  destroy: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'delete'> => ({
    url: buildUrl('/projects/:id', params, options),
    method: 'delete',
  }),
}
