// Typelizer digest 078c6a7f05850d0552deba28ea4dacc0
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../runtime'
import { buildUrl } from '../runtime'

export default {
  /** GET /projects/:project_id/errors */
  index: (
    params: { projectId: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/projects/:project_id/errors', params, options),
    method: 'get',
  }),
}
