// Typelizer digest bcab2cabefbdcee23bb5a30f18b5bb6a
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../runtime'
import { buildUrl } from '../runtime'

export default {
  /** GET /projects/:project_id/versions */
  index: (
    params: { projectId: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/projects/:project_id/versions', params, options),
    method: 'get',
  }),
}
